from secprint import SectionPrinter as Spt
from secprint import Color

Spt.enter_section('Mega section of the dead', color=Color.BLINK)
Spt.enter_section('Normal section', Color.RED)
Spt.enter_section('Subsection', Color.GREEN)
for i in range(15):
    Spt.print('This ', end='')
    Spt.print('is ', blink=True, print_headers=False, end='')
    Spt.print('dope ', print_headers=False, end='')
    Spt.print('shit', print_headers=False, blink=True)
Spt.exit_section()

print('NONE - ' + Color.NONE + 'YOOOO' + Color.END)
print('BLACK - ' + Color.BLACK + 'YOOOO' + Color.END)
print('DARK_GRAY - ' + Color.DARK_GRAY + 'YOOOO' + Color.END)
print('GRAY - ' + Color.GRAY + 'YOOOO' + Color.END)
print('WHITE - ' + Color.WHITE + 'YOOOO' + Color.END)
print('RED - ' + Color.RED + 'YOOOO' + Color.END)
print('GREEN - ' + Color.GREEN + 'YOOOO' + Color.END)
print('YELLOW - ' + Color.YELLOW + 'YOOOO' + Color.END)
print('BLUE - ' + Color.BLUE + 'YOOOO' + Color.END)
print('PURPLE - ' + Color.PURPLE + 'YOOOO' + Color.END)
print('CYAN - ' + Color.CYAN + 'YOOOO' + Color.END)
print('DARK_RED - ' + Color.DARK_RED + 'YOOOO' + Color.END)
print('DARK_GREEN - ' + Color.DARK_GREEN + 'YOOOO' + Color.END)
print('DARK_YELLOW - ' + Color.DARK_YELLOW + 'YOOOO' + Color.END)
print('DARK_BLUE - ' + Color.DARK_BLUE + 'YOOOO' + Color.END)
print('DARK_PURPLE - ' + Color.DARK_PURPLE + 'YOOOO' + Color.END)
print('DARK_CYAN - ' + Color.DARK_CYAN + 'YOOOO' + Color.END)